on:
  push:
    branches: 
      - code

jobs:
  BUILD:
    runs-on: [ubuntu-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # - name: npm
      #   run: |
      #     npm install
      #     npm run build

      # - name: artefact
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: buildOutcome
      #     path: build

      - name: git
        run: |
          git init
          git config  user.email grandalf6@gmail.com
          git config user.email
          git config user.name grandalf6
          git config user.name
          git checkout -b auto
          echo hello > hello.txt
          git add .
          git status
          git commit -m "automated commit"
          git status
          git remote remove origin
          git remote add origin 'https://${{ secrets.GITHUB_TOKEN }}@github.com/balbinasurma/balbinasurma.github.io.git'
          git remote -v
          git push --set-upstream origin auto