on:
  push:
    branches: 
      - code

jobs:
  BUILD:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: |
          npm install
          npm run build
          
      - uses: actions/upload-artifact@v1
        with:
          name: buildOutcome
          path: build

  GIT:
    needs: [BUILD]
    runs-on: [ubuntu-latest]

    steps:
      - run: git init
      - run: git remote add origin https://grandalf6:${{ secrets.GITHUB_TOKEN}}@github.com/balbinasurma/balbinasurma.github.io.git
      - run: git config user.email ${{secrets.email}}
      - run: git config user.name ${{secrets.user}}

      - run: git checkout -b auto
      - uses: actions/download-artifact@v1.0.0
        with:
          name: buildOutcome
          path: /build

      - run: git status
      - run: git add .
      - run: git status
      - run: dir
      - run: git commit -m "autoCommit"
      - run: git push --set-upstream origin auto


      # - name: npm
      #   run: |
      #     npm install
      #     npm run build

      # - name: artefact
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: buildOutcome
      #     path: build

      # - name: git
      #   run: |
      #     git init
      #     git config  user.email grandalf6@gmail.com
      #     git config user.name grandalf6
      #     git checkout -b auto
      #     echo hello > hello.txt
      #     git add .
      #     git commit -m "automated commit"
      #     git remote remove origin
      #     git remote add origin 'https://github.com/balbinasurma/balbinasurma.github.io.git'
      #     git remote -v
      #     git push --set-upstream origin auto