on:
  push:
    branches: 
      - code

jobs:
  BUILD:
    runs-on: [ubuntu-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: [12.x]

      - name: npm
        run: |
          npm install
          npm run build
          
      - name: artefact
        uses: actions/upload-artifact@v1
        with:
          name: buildOutcome
          path: build


  PUSH:
    needs: [BUILD]
    runs-on: [ubuntu-latest]
    steps:
      - run: git status