on:
  push:
    branches: 
      - code

jobs:
  BUILD:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@v1
        with:
          name: buildOutcome
          path: build

  GIT:
    needs: [BUILD]
    runs-on: [ubuntu-latest]
    steps:
      - run: git init
      - run: git remote add origin https://grandalf6:${{ secrets.GITHUB_TOKEN}}@github.com/balbinasurma/balbinasurma.github.io.git
      - run: git config user.email ${{secrets.email}}
      - run: git config user.name ${{secrets.user}}

      - run: git checkout -b auto
      - uses: actions/download-artifact@v1.0.0
        with:
          name: buildOutcome
          path: ./
      - run: git add .
      - run: git commit -m "autoCommit"
      - run: git show-ref
      - run: git push --force origin HEAD:master