on:
  push:
    branches: 
      - code

jobs:
  test1:
    name: test1
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: ci1
      run: |
        npm install
        npm run build