on:
  push:
    branches: 
      - code

jobs:
  GIT:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: step one access folders
      run: git status
    - run: git remote -v
