on:
  push:
    branches: 
      - code

jobs:
  test1:
    name: test1
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm
        run: |
          npm install
          npm run build
      - name: artefact
        uses: actions/upload-artifact@v1
        with:
          name: alfa
          path: build
