on:
  push:
    branches: 
      - code

jobs:
  # BUILD:
  #   runs-on: [ubuntu-latest]

  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v1

  #     - name: node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 12.x

  GIT:
    runs-on: [ubuntu-latest]

    steps:
      - run: git init
      - run: git remote add origin https://grandalf6:${{ secrets.GITHUB_TOKEN}}@github.com/balbinasurma/test.git
      - run: git checkout -b auto
      - run: echo "auto" > auto.html
      - run: git add .
      - run: git config user.email grandalf6@gmail.com
      - run: git config user.name grandalf6
      - run: git config user

      # - name: npm
      #   run: |
      #     npm install
      #     npm run build

      # - name: artefact
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: buildOutcome
      #     path: build

      # - name: git
      #   run: |
      #     git init
      #     git config  user.email grandalf6@gmail.com
      #     git config user.name grandalf6
      #     git checkout -b auto
      #     echo hello > hello.txt
      #     git add .
      #     git commit -m "automated commit"
      #     git remote remove origin
      #     git remote add origin 'https://github.com/balbinasurma/balbinasurma.github.io.git'
      #     git remote -v
      #     git push --set-upstream origin auto